### ISSUE TITLE
gollum seems not start with --mathjax

### ISSUE THREAD

**Issue by benlw** [arpaulnet/gollum#1]
When I create new markdown page, and type $x^2$, the equations Cann't render rightly, maybe arpaulnet/gollum container should start up with --mathjax?

Thank you!

here is the yml file.
```
#...
services:
  gollum:
    image: arpaulnet/gollum
    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Denver
    restart: unless-stopped
```

and  images is `arpaulnet/gollum`, 'gollum --version'. is `Gollum 5.2.3`

**Comment by arpaulnet** [comment]
You can pass whichever flags you want by overriding the command.  Try this:

```yaml
#...
services:
  gollum:
    image: arpaulnet/gollum
    command: ["gollum", "--mathjax"]
    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Denver
    restart: unless-stopped
```
